#!/usr/bin/env python3

import sys
from solver import solve

if len(sys.argv) == 2:
    if sys.argv[1] == '--init':
        print('Success: all pruning tables have been created.')
    else:
        solution = solve(sys.argv[1])
        print(solution)
else:
    print('Usage: kociemba-2x2x2 <cubestring>\nFor example:\nkociemba-2x2x2 DDUUBFRURRUFLDDLRFLBLBFB')